
# This file is automatically generated, you probably don't want to edit this

bttestOneSOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bttestOneSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            bfType = "BF10",
            bfPrior = 0.707,
            testValue = 0,
            hypothesis = "dt",
            meanDiff = FALSE,
            effectSize = FALSE,
            ci = FALSE,
            ciWidth = 95,
            desc = FALSE,
            plots = FALSE,
            miss = "perAnalysis",
            pp = FALSE,
            robust = FALSE,
            assum = FALSE, ...) {

            super$initialize(
                package='BayesFactor',
                name='bttestOneS',
                requiresData=TRUE,
                ...)
        
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                rejectInf=FALSE)
            private$..bfType <- jmvcore::OptionList$new(
                "bfType",
                bfType,
                options=list(
                    "BF10",
                    "BF01"),
                default="BF10")
            private$..bfPrior <- jmvcore::OptionNumber$new(
                "bfPrior",
                bfPrior,
                default=0.707,
                min=0.5,
                max=2)
            private$..testValue <- jmvcore::OptionNumber$new(
                "testValue",
                testValue,
                default=0)
            private$..hypothesis <- jmvcore::OptionList$new(
                "hypothesis",
                hypothesis,
                options=list(
                    "dt",
                    "gt",
                    "lt"),
                default="dt")
            private$..meanDiff <- jmvcore::OptionBool$new(
                "meanDiff",
                meanDiff,
                default=FALSE)
            private$..effectSize <- jmvcore::OptionBool$new(
                "effectSize",
                effectSize,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..plots <- jmvcore::OptionBool$new(
                "plots",
                plots,
                default=FALSE)
            private$..miss <- jmvcore::OptionList$new(
                "miss",
                miss,
                options=list(
                    "perAnalysis",
                    "listwise"),
                default="perAnalysis")
            private$..pp <- jmvcore::OptionBool$new(
                "pp",
                pp,
                default=FALSE)
            private$..robust <- jmvcore::OptionBool$new(
                "robust",
                robust,
                default=FALSE)
            private$..assum <- jmvcore::OptionBool$new(
                "assum",
                assum,
                default=FALSE)
        
            self$.addOption(private$..vars)
            self$.addOption(private$..bfType)
            self$.addOption(private$..bfPrior)
            self$.addOption(private$..testValue)
            self$.addOption(private$..hypothesis)
            self$.addOption(private$..meanDiff)
            self$.addOption(private$..effectSize)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..desc)
            self$.addOption(private$..plots)
            self$.addOption(private$..miss)
            self$.addOption(private$..pp)
            self$.addOption(private$..robust)
            self$.addOption(private$..assum)
        }),
    active = list(
        vars = function() private$..vars$value,
        bfType = function() private$..bfType$value,
        bfPrior = function() private$..bfPrior$value,
        testValue = function() private$..testValue$value,
        hypothesis = function() private$..hypothesis$value,
        meanDiff = function() private$..meanDiff$value,
        effectSize = function() private$..effectSize$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        desc = function() private$..desc$value,
        plots = function() private$..plots$value,
        miss = function() private$..miss$value,
        pp = function() private$..pp$value,
        robust = function() private$..robust$value,
        assum = function() private$..assum$value),
    private = list(
        ..vars = NA,
        ..bfType = NA,
        ..bfPrior = NA,
        ..testValue = NA,
        ..hypothesis = NA,
        ..meanDiff = NA,
        ..effectSize = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..desc = NA,
        ..plots = NA,
        ..miss = NA,
        ..pp = NA,
        ..robust = NA,
        ..assum = NA)
)

bttestOneSResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        ttest = function() private$..ttest,
        descriptives = function() private$..descriptives,
        plots = function() private$..plots),
    private = list(
        ..ttest = NA,
        ..descriptives = NA,
        ..plots = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian One Sample T-Test")
            private$..ttest <- jmvcore::Table$new(
                options=options,
                name="ttest",
                title="One Sample T-Test",
                rows="(vars)",
                clearWith=list(
                    "hypothesis",
                    "testValue",
                    "miss"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="t", 
                        `title`="t"),
                    list(
                        `name`="df", 
                        `title`="df"),
                    list(
                        `name`="bf10", 
                        `title`="BF\u2081\u2080", 
                        `visible`="(bfType:BF10)"),
                    list(
                        `name`="bf01", 
                        `title`="BF\u2080\u2081", 
                        `visible`="(bfType:BF01)"),
                    list(
                        `name`="err", 
                        `title`="error %"),
                    list(
                        `name`="md", 
                        `title`="Mean difference", 
                        `type`="number", 
                        `visible`="(meanDiff)"),
                    list(
                        `name`="es", 
                        `title`="Cohen's d", 
                        `type`="number", 
                        `visible`="(effectSize)"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `superTitle`="% Credible Interval", 
                        `type`="number", 
                        `visible`="(ci)"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `superTitle`="% Credible Interval", 
                        `type`="number", 
                        `visible`="(ci)")))
            private$..descriptives <- jmvcore::Table$new(
                options=options,
                name="descriptives",
                title="Descriptives",
                visible="(desc)",
                rows="(vars)",
                clearWith=list(
                    "miss"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text"),
                    list(
                        `name`="num", 
                        `title`="N", 
                        `type`="number"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="median", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number")))
            private$..plots <- jmvcore::Image$new(
                options=options,
                name="plots",
                title="Plots",
                visible="(plots)",
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "miss"))
            self$add(private$..ttest)
            self$add(private$..descriptives)
            self$add(private$..plots)}))

bttestOneSBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bttestOneSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'BayesFactor',
                name = 'bttestOneS',
                version = c(1,0,0),
                options = options,
                results = bttestOneSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE)
        }))

#' Bayesian One Sample T-Test
#'
#' 
#'
#' @examples
#' data('ToothGrowth')
#' 
#' bttestOneS(ToothGrowth, vars = c('len', 'dose'))
#' 
#' @param data the data as a data frame
#' @param vars a vector of strings naming the variables of interest in 
#'   \code{data}
#' @param bfType \code{'BF10'} (default) or \code{'BF01'} 
#' @param bfPrior a number between 0.5 and 2 (default 0.707), the prior width 
#'   to use in calculating Bayes factors 
#' @param testValue a number specifying the value of the null hypothesis
#' @param hypothesis \code{'dt'} (default), \code{'gt'} or \code{'lt'}, the 
#'   alternative hypothesis; different to \code{testValue}, greater than 
#'   \code{testValue}, and less than \code{testValue} respectively 
#' @param meanDiff \code{TRUE} or \code{FALSE} (default), provide means and 
#'   standard deviations 
#' @param effectSize \code{TRUE} or \code{FALSE} (default), provide effect 
#'   sizes 
#' @param ci \code{TRUE} or \code{FALSE} (default), provide confidence 
#'   intervals 
#' @param ciWidth a number between 50 and 99.9 (default: 95), the width of 
#'   confidence intervals 
#' @param desc \code{TRUE} or \code{FALSE} (default), provide descriptive 
#'   statistics 
#' @param plots \code{TRUE} or \code{FALSE} (default), provide descriptive 
#'   plots 
#' @param miss \code{'perAnalysis'} or \code{'listwise'}, how to handle 
#'   missing values; \code{'perAnalysis'} excludes missing values for individual 
#'   dependent variables, \code{'listwise'} excludes a row from all analyses if 
#'   one of its entries is missing. 
#' @param pp .
#' @param robust .
#' @param assum .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ttest} \tab \tab \tab \tab \tab a table containing the t-test results \cr
#'   \code{results$descriptives} \tab \tab \tab \tab \tab a table containing the descriptives \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an image of the descriptive plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ttest$asDF}
#'
#' \code{as.data.frame(results$ttest)}
#'
#' @export
bttestOneS <- function(
    data,
    vars,
    bfType = "BF10",
    bfPrior = 0.707,
    testValue = 0,
    hypothesis = "dt",
    meanDiff = FALSE,
    effectSize = FALSE,
    ci = FALSE,
    ciWidth = 95,
    desc = FALSE,
    plots = FALSE,
    miss = "perAnalysis",
    pp = FALSE,
    robust = FALSE,
    assum = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('bttestOneS requires jmvcore to be installed (restart may be required)')

    options <- bttestOneSOptions$new(
        vars = vars,
        bfType = bfType,
        bfPrior = bfPrior,
        testValue = testValue,
        hypothesis = hypothesis,
        meanDiff = meanDiff,
        effectSize = effectSize,
        ci = ci,
        ciWidth = ciWidth,
        desc = desc,
        plots = plots,
        miss = miss,
        pp = pp,
        robust = robust,
        assum = assum)

    results <- bttestOneSResults$new(
        options = options)

    analysis <- bttestOneSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
