
# This file is automatically generated, you probably don't want to edit this

bttestPSOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bttestPSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pairs = NULL,
            bfType = "BF10",
            bfPrior = 0.707,
            hypothesis = "different",
            meanDiff = FALSE,
            effectSize = FALSE,
            ci = FALSE,
            ciWidth = 95,
            desc = FALSE,
            plots = FALSE,
            miss = "perAnalysis",
            pp = FALSE,
            robust = FALSE,
            assum = FALSE, ...) {

            super$initialize(
                package='BayesFactor',
                name='bttestPS',
                requiresData=TRUE,
                ...)
        
            private$..pairs <- jmvcore::OptionPairs$new(
                "pairs",
                pairs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..bfType <- jmvcore::OptionList$new(
                "bfType",
                bfType,
                options=list(
                    "BF10",
                    "BF01"),
                default="BF10")
            private$..bfPrior <- jmvcore::OptionNumber$new(
                "bfPrior",
                bfPrior,
                default=0.707,
                min=0.5,
                max=2)
            private$..hypothesis <- jmvcore::OptionList$new(
                "hypothesis",
                hypothesis,
                options=list(
                    "different",
                    "oneGreater",
                    "twoGreater"),
                default="different")
            private$..meanDiff <- jmvcore::OptionBool$new(
                "meanDiff",
                meanDiff,
                default=FALSE)
            private$..effectSize <- jmvcore::OptionBool$new(
                "effectSize",
                effectSize,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..plots <- jmvcore::OptionBool$new(
                "plots",
                plots,
                default=FALSE)
            private$..miss <- jmvcore::OptionList$new(
                "miss",
                miss,
                options=list(
                    "perAnalysis",
                    "listwise"),
                default="perAnalysis")
            private$..pp <- jmvcore::OptionBool$new(
                "pp",
                pp,
                default=FALSE)
            private$..robust <- jmvcore::OptionBool$new(
                "robust",
                robust,
                default=FALSE)
            private$..assum <- jmvcore::OptionBool$new(
                "assum",
                assum,
                default=FALSE)
        
            self$.addOption(private$..pairs)
            self$.addOption(private$..bfType)
            self$.addOption(private$..bfPrior)
            self$.addOption(private$..hypothesis)
            self$.addOption(private$..meanDiff)
            self$.addOption(private$..effectSize)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..desc)
            self$.addOption(private$..plots)
            self$.addOption(private$..miss)
            self$.addOption(private$..pp)
            self$.addOption(private$..robust)
            self$.addOption(private$..assum)
        }),
    active = list(
        pairs = function() private$..pairs$value,
        bfType = function() private$..bfType$value,
        bfPrior = function() private$..bfPrior$value,
        hypothesis = function() private$..hypothesis$value,
        meanDiff = function() private$..meanDiff$value,
        effectSize = function() private$..effectSize$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        desc = function() private$..desc$value,
        plots = function() private$..plots$value,
        miss = function() private$..miss$value,
        pp = function() private$..pp$value,
        robust = function() private$..robust$value,
        assum = function() private$..assum$value),
    private = list(
        ..pairs = NA,
        ..bfType = NA,
        ..bfPrior = NA,
        ..hypothesis = NA,
        ..meanDiff = NA,
        ..effectSize = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..desc = NA,
        ..plots = NA,
        ..miss = NA,
        ..pp = NA,
        ..robust = NA,
        ..assum = NA)
)

bttestPSResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        ttest = function() private$..ttest,
        desc = function() private$..desc,
        plots = function() private$..plots),
    private = list(
        ..ttest = NA,
        ..desc = NA,
        ..plots = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian Paired Samples T-Test")
            private$..ttest <- jmvcore::Table$new(
                options=options,
                name="ttest",
                title="Paired Samples T-Test",
                rows="(pairs)",
                clearWith=list(
                    "miss",
                    "hypothesis",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="var2", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="t", 
                        `title`="t"),
                    list(
                        `name`="df", 
                        `title`="df"),
                    list(
                        `name`="bf10", 
                        `title`="BF\u2081\u2080", 
                        `visible`="(bfType:BF10)"),
                    list(
                        `name`="bf01", 
                        `title`="BF\u2080\u2081", 
                        `visible`="(bfType:BF01)"),
                    list(
                        `name`="err", 
                        `title`="error %"),
                    list(
                        `name`="md", 
                        `title`="Mean difference", 
                        `type`="number", 
                        `visible`="(meanDiff)"),
                    list(
                        `name`="sed", 
                        `title`="SE difference", 
                        `type`="number", 
                        `visible`="(meanDiff)"),
                    list(
                        `name`="es", 
                        `title`="Cohen's d", 
                        `type`="number", 
                        `visible`="(effectSize)"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `superTitle`="% Credible Interval", 
                        `type`="number", 
                        `visible`="(ci)"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `superTitle`="% Credible Interval", 
                        `type`="number", 
                        `visible`="(ci)")))
            private$..desc <- jmvcore::Table$new(
                options=options,
                name="desc",
                title="Descriptives",
                visible="(desc)",
                clearWith=list(
                    "miss"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `content`=".", 
                        `type`="text"),
                    list(
                        `name`="num", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="m", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="med", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number")))
            private$..plots <- jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                visible="(plots)",
                items="(pairs)",
                template=jmvcore::Image$new(
                    options=options,
                    renderFun=".plot",
                    clearWith=list(
                        "miss")))
            self$add(private$..ttest)
            self$add(private$..desc)
            self$add(private$..plots)}))

bttestPSBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bttestPSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'BayesFactor',
                name = 'bttestPS',
                version = c(1,0,0),
                options = options,
                results = bttestPSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE)
        }))

#' Bayesian Paired Samples T-Test
#'
#' 
#'
#' @examples
#' \dontrun{
#' data('bugs', package = 'jmv')
#' 
#' bttestPS(bugs, pairs = list(
#'         list(i1 = 'LDLF', i2 = 'LDHF')))
#' }
#' @param data the data as a data frame
#' @param pairs a list of lists specifying the pairs of measurement in 
#'   \code{data}
#' @param bfType \code{'BF10'} (default) or \code{'BF01'} 
#' @param bfPrior a number between 0.5 and 2 (default 0.707), the prior width 
#'   to use in calculating Bayes factors 
#' @param hypothesis \code{'different'} (default), \code{'oneGreater'} or 
#'   \code{'twoGreater'}, the alternative hypothesis; group 1 different to group 
#'   2, group 1 greater than group 2, and group 2 greater than group 1 
#'   respectively 
#' @param meanDiff \code{TRUE} or \code{FALSE} (default), provide means and 
#'   standard errors 
#' @param effectSize \code{TRUE} or \code{FALSE} (default), provide effect 
#'   sizes 
#' @param ci \code{TRUE} or \code{FALSE} (default), provide credible intervals 
#' @param ciWidth a number between 50 and 99.9 (default: 95), the width of 
#'   credible intervals 
#' @param desc \code{TRUE} or \code{FALSE} (default), provide descriptive 
#'   statistics 
#' @param plots \code{TRUE} or \code{FALSE} (default), provide descriptive 
#'   plots 
#' @param miss \code{'perAnalysis'} or \code{'listwise'}, how to handle 
#'   missing values; \code{'perAnalysis'} excludes missing values for individual 
#'   dependent variables, \code{'listwise'} excludes a row from all analyses if 
#'   one of its entries is missing. 
#' @param pp .
#' @param robust .
#' @param assum .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ttest} \tab \tab \tab \tab \tab a table containing the t-test results \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table containing the descriptives \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of the descriptive plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ttest$asDF}
#'
#' \code{as.data.frame(results$ttest)}
#'
#' @export
bttestPS <- function(
    data,
    pairs,
    bfType = "BF10",
    bfPrior = 0.707,
    hypothesis = "different",
    meanDiff = FALSE,
    effectSize = FALSE,
    ci = FALSE,
    ciWidth = 95,
    desc = FALSE,
    plots = FALSE,
    miss = "perAnalysis",
    pp = FALSE,
    robust = FALSE,
    assum = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('bttestPS requires jmvcore to be installed (restart may be required)')

    options <- bttestPSOptions$new(
        pairs = pairs,
        bfType = bfType,
        bfPrior = bfPrior,
        hypothesis = hypothesis,
        meanDiff = meanDiff,
        effectSize = effectSize,
        ci = ci,
        ciWidth = ciWidth,
        desc = desc,
        plots = plots,
        miss = miss,
        pp = pp,
        robust = robust,
        assum = assum)

    results <- bttestPSResults$new(
        options = options)

    analysis <- bttestPSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
